
version: "3.8"

services:
  mysqldb:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fundacjaprojekt
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
  app:
    build: .
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
        - DATABASE_HOST=mysqldb
        - DATABASE_USER=user
        - DATABASE_PASSWORD=password
        - DATABASE_NAME=fundacjaprojekt
        - DATABASE_PORT=3307
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/fundacjaprojekt?useSSL=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME=user
        - SPRING_DATASOURCE_PASSWORD=password
volumes:
  db:

