spring:
  base:
    uri: http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fundacjaprojekt?useSSL=false&allowPublicKeyRetrieval=true
    username: hbstudent
    password: hbstudent
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: eacc77f07a128f
    password: ba91adf666a932
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    messages:
      basename: i18n/messages
      encoding: UTF-8





